name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Resolve SITEURL for GitHub Pages
        id: siteurl
        shell: bash
        run: |
          REPO_NAME="${GITHUB_REPOSITORY#*/}"
          OWNER="${GITHUB_REPOSITORY%/*}"
          if [[ "$REPO_NAME" == *.github.io ]]; then
            SITEURL="https://$REPO_NAME"
          else
            SITEURL="https://$OWNER.github.io/$REPO_NAME"
          fi
          echo "SITEURL=$SITEURL" >> $GITHUB_OUTPUT

      - name: Build site with Pelican
        env:
          SITEURL: ${{ steps.siteurl.outputs.SITEURL }}
        run: |
          pelican -s publishconf.py

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./output

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
